pool:
    name: Hosted VS2017
    demands: npm

pr: none

trigger:
    branches:
        exclude:
            - "*"
    tags:
        include:
            - v*-internal

steps:
    - task: Npm@1
      displayName: "npm install"
      inputs:
          verbose: false

    - script: npm run build

    - script: npm run package-release-internal

    - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishExtension@1
      displayName: "Publish Extension"
      inputs:
          connectedServiceName: Marketplace hangy
          fileType: vsix
          vsixFile: "hangy.estimate-*.vsix"
          updateTasksVersion: false
