name: Build & Deploy
on:
    push:
        branches:
            - main
        tags:
            - "v*"
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14
            - run: npm ci
            - run: npm run lint
            - run: npm run build
            - run: npm run package-dev
              if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
            - run: npm run package-release
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
            - name: Upload VSIX Build Artifact
              uses: actions/upload-artifact@v2.2.3
              with:
                  name: vsix
                  path: ${{ github.workspace }}/*.vsix
                  if-no-files-found: error
            - uses: marvinpinto/action-automatic-releases@v1.1.1
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: Development Build
                  files: |
                      LICENSE
                      *.vsix
            - uses: marvinpinto/action-automatic-releases@v1.1.1
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: |
                      LICENSE
                      *.vsix
